//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.01 at 10:01:19 AM IST 
//


package com.soap.card.interfaces;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cardInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cardInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cardno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardholdername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardbalance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="cardissueddate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardexpirydate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankid" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cardInfo", propOrder = {
    "cardno",
    "cardholdername",
    "cardbalance",
    "cardissueddate",
    "cardexpirydate",
    "cardstatus",
    "bankid"
})
public class CardInfo {

    @XmlElement(required = true)
    protected String cardno;
    @XmlElement(required = true)
    protected String cardholdername;
    protected double cardbalance;
    @XmlElement(required = true)
    protected String cardissueddate;
    @XmlElement(required = true)
    protected String cardexpirydate;
    @XmlElement(required = true)
    protected String cardstatus;
    protected short bankid;

    /**
     * Gets the value of the cardno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * Sets the value of the cardno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardno(String value) {
        this.cardno = value;
    }

    /**
     * Gets the value of the cardholdername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholdername() {
        return cardholdername;
    }

    /**
     * Sets the value of the cardholdername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholdername(String value) {
        this.cardholdername = value;
    }

    /**
     * Gets the value of the cardbalance property.
     * 
     */
    public double getCardbalance() {
        return cardbalance;
    }

    /**
     * Sets the value of the cardbalance property.
     * 
     */
    public void setCardbalance(double value) {
        this.cardbalance = value;
    }

    /**
     * Gets the value of the cardissueddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardissueddate() {
        return cardissueddate;
    }

    /**
     * Sets the value of the cardissueddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardissueddate(String value) {
        this.cardissueddate = value;
    }

    /**
     * Gets the value of the cardexpirydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardexpirydate() {
        return cardexpirydate;
    }

    /**
     * Sets the value of the cardexpirydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardexpirydate(String value) {
        this.cardexpirydate = value;
    }

    /**
     * Gets the value of the cardstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardstatus() {
        return cardstatus;
    }

    /**
     * Sets the value of the cardstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardstatus(String value) {
        this.cardstatus = value;
    }

    /**
     * Gets the value of the bankid property.
     * 
     */
    public short getBankid() {
        return bankid;
    }

    /**
     * Sets the value of the bankid property.
     * 
     */
    public void setBankid(short value) {
        this.bankid = value;
    }

}
